refactor allSelected -> isAllChecked()
allSelected field is changed to isAllChecked() method call
because of error below:

ERROR in node_modules/primeng/multiselect/primeng-multiselect.d.ts.MultiSelect.html(26,109): Property 'allSelected' does not exist on type 'MultiSelect'.